<?php

use Illuminate\Database\Seeder;
use App\Food;

class FoodTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // for($i = 1; $i < 34; $i++){
        //     $name = 'food' .str_random(5) ;
        //     Food::create([
        //         'name' => $name,
        //         'image' => rand(1,13) . '.jpg',
        //         'slug' => str_slug($name),
        //         'description' => str_random(15),
        //         'content' => str_random(40),
        //         'price' => rand(1, 100) * 1000,
        //         'top' => '1',
        //         'new'=> '1',
        //         'promotion_id' => rand(1,8),
        //         'created_at' => new DateTime,
        //         'updated_at' => new DateTime,
        //     ]);
        // }
        DB::table('foods')->insert([
            [
                'name' => 'Bánh Cắt Nhỏ 1', 
                'slug' => 'banh-cat-nho-1',
                'image' => '1.1.jpg',
                'description' => str_random(15),
                'content' => str_random(40),
                'price' => rand(1, 100) * 1000,
                'top' => '1',
                'new'=> '1',
                'promotion_id' => rand(1,8),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'name' => 'Bánh Cắt Nhỏ 2', 
                'slug' => 'banh-cat-nho-2',
                'image' => '1.2.jpg',
                'description' => str_random(15),
                'content' => str_random(40),
                'price' => rand(1, 100) * 1000,
                'top' => '1',
                'new'=> '1',
                'promotion_id' => rand(1,8),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'name' => 'Bánh Cắt Nhỏ 3', 
                'slug' => 'banh-cat-nho-3',
                'image' => '1.3.jpg',
                'description' => str_random(15),
                'content' => str_random(40),
                'price' => rand(1, 100) * 1000,
                'top' => '1',
                'new'=> '1',
                'promotion_id' => rand(1,8),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'name' => 'Bánh Cắt Nhỏ 4', 
                'slug' => 'banh-cat-nho-4',
                'image' => '1.4.jpg',
                'description' => str_random(15),
                'content' => str_random(40),
                'price' => rand(1, 100) * 1000,
                'top' => '1',
                'new'=> '1',
                'promotion_id' => rand(1,8),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'name' => 'Bánh Hình Trái Tim 1', 
                'slug' => 'banh-hinh-trai-tim-1',
                'image' => '2.1.jpg',
                'description' => str_random(15),
                'content' => str_random(40),
                'price' => rand(1, 100) * 1000,
                'top' => '1',
                'new'=> '1',
                'promotion_id' => rand(1,8),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'name' => 'Bánh Hình Trái Tim 2', 
                'slug' => 'banh-hinh-trai-tim-2',
                'image' => '2.2.jpg',
                'description' => str_random(15),
                'content' => str_random(40),
                'price' => rand(1, 100) * 1000,
                'top' => '1',
                'new'=> '1',
                'promotion_id' => rand(1,8),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'name' => 'Bánh Hình Trái Tim 3', 
                'slug' => 'banh-hinh-trai-tim-3',
                'image' => '2.3.jpg',
                'description' => str_random(15),
                'content' => str_random(40),
                'price' => rand(1, 100) * 1000,
                'top' => '1',
                'new'=> '1',
                'promotion_id' => rand(1,8),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'name' => 'Bánh Hình Trái Tim 4', 
                'slug' => 'banh-hinh-trai-tim-4',
                'image' => '2.4.jpg',
                'description' => str_random(15),
                'content' => str_random(40),
                'price' => rand(1, 100) * 1000,
                'top' => '1',
                'new'=> '1',
                'promotion_id' => rand(1,8),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'name' => 'Bánh Mì 1', 
                'slug' => 'banh-mi-1',
                'image' => '3.1.jpg',
                'description' => str_random(15),
                'content' => str_random(40),
                'price' => rand(1, 100) * 1000,
                'top' => '1',
                'new'=> '1',
                'promotion_id' => rand(1,8),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'name' => 'Bánh Mì 2', 
                'slug' => 'banh-mi-2',
                'image' => '3.2.jpg',
                'description' => str_random(15),
                'content' => str_random(40),
                'price' => rand(1, 100) * 1000,
                'top' => '1',
                'new'=> '1',
                'promotion_id' => rand(1,8),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'name' => 'Bánh Mì 3', 
                'slug' => 'banh-mi-3',
                'image' => '3.3.jpg',
                'description' => str_random(15),
                'content' => str_random(40),
                'price' => rand(1, 100) * 1000,
                'top' => '1',
                'new'=> '1',
                'promotion_id' => rand(1,8),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'name' => 'Bánh Noel 1', 
                'slug' => 'banh-noel-1',
                'image' => '4.1.jpg',
                'description' => str_random(15),
                'content' => str_random(40),
                'price' => rand(1, 100) * 1000,
                'top' => '1',
                'new'=> '1',
                'promotion_id' => rand(1,8),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'name' => 'Bánh Noel 2', 
                'slug' => 'banh-noel-2',
                'image' => '4.2.jpg',
                'description' => str_random(15),
                'content' => str_random(40),
                'price' => rand(1, 100) * 1000,
                'top' => '1',
                'new'=> '1',
                'promotion_id' => rand(1,8),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'name' => 'Bánh Sinh Nhật 1', 
                'slug' => 'banh-sinh-nhat-1',
                'image' => '5.1.jpg',
                'description' => str_random(15),
                'content' => str_random(40),
                'price' => rand(1, 100) * 1000,
                'top' => '1',
                'new'=> '1',
                'promotion_id' => rand(1,8),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'name' => 'Bánh Sinh Nhật 2', 
                'slug' => 'banh-sinh-nhat-2',
                'image' => '5.2.jpg',
                'description' => str_random(15),
                'content' => str_random(40),
                'price' => rand(1, 100) * 1000,
                'top' => '1',
                'new'=> '1',
                'promotion_id' => rand(1,8),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'name' => 'Bánh Sinh Nhật 3', 
                'slug' => 'banh-sinh-nhat-3',
                'image' => '5.3.jpg',
                'description' => str_random(15),
                'content' => str_random(40),
                'price' => rand(1, 100) * 1000,
                'top' => '1',
                'new'=> '1',
                'promotion_id' => rand(1,8),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'name' => 'Bánh Sinh Nhật 4', 
                'slug' => 'banh-sinh-nhat-4',
                'image' => '5.4.jpg',
                'description' => str_random(15),
                'content' => str_random(40),
                'price' => rand(1, 100) * 1000,
                'top' => '1',
                'new'=> '1',
                'promotion_id' => rand(1,8),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'name' => 'Cupcakes 1', 
                'slug' => 'cup-cakes-1',
                'image' => '6.1.jpg',
                'description' => str_random(15),
                'content' => str_random(40),
                'price' => rand(1, 100) * 1000,
                'top' => '1',
                'new'=> '1',
                'promotion_id' => rand(1,8),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'name' => 'Cupcakes 2', 
                'slug' => 'cup-cakes-2',
                'image' => '6.2.jpg',
                'description' => str_random(15),
                'content' => str_random(40),
                'price' => rand(1, 100) * 1000,
                'top' => '1',
                'new'=> '1',
                'promotion_id' => rand(1,8),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'name' => 'Cupcakes 3', 
                'slug' => 'cup-cakes-3',
                'image' => '6.3.jpg',
                'description' => str_random(15),
                'content' => str_random(40),
                'price' => rand(1, 100) * 1000,
                'top' => '1',
                'new'=> '1',
                'promotion_id' => rand(1,8),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
        ]);
    }

}
